name: Deploy EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform Apply (environments/dev)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -var-file=dev.tfvars -out=plan.tfplan

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -input=false -auto-approve plan.tfplan
